# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/longnguyen/Downloads/ppsspp/ppsspp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/longnguyen/Downloads/ppsspp/ppsspp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/longnguyen/Downloads/ppsspp/ppsspp/CMakeFiles /Users/longnguyen/Downloads/ppsspp/ppsspp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/longnguyen/Downloads/ppsspp/ppsspp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named retro_game

# Build rule for target.
retro_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 retro_game
.PHONY : retro_game

# fast build rule for target.
retro_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/build
.PHONY : retro_game/fast

background/background.obj: background/background.c.obj
.PHONY : background/background.obj

# target to build an object file
background/background.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/background/background.c.obj
.PHONY : background/background.c.obj

background/background.i: background/background.c.i
.PHONY : background/background.i

# target to preprocess a source file
background/background.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/background/background.c.i
.PHONY : background/background.c.i

background/background.s: background/background.c.s
.PHONY : background/background.s

# target to generate assembly for a file
background/background.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/background/background.c.s
.PHONY : background/background.c.s

enemies/enemy.obj: enemies/enemy.c.obj
.PHONY : enemies/enemy.obj

# target to build an object file
enemies/enemy.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/enemy.c.obj
.PHONY : enemies/enemy.c.obj

enemies/enemy.i: enemies/enemy.c.i
.PHONY : enemies/enemy.i

# target to preprocess a source file
enemies/enemy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/enemy.c.i
.PHONY : enemies/enemy.c.i

enemies/enemy.s: enemies/enemy.c.s
.PHONY : enemies/enemy.s

# target to generate assembly for a file
enemies/enemy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/enemy.c.s
.PHONY : enemies/enemy.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/main.c.s
.PHONY : main.c.s

player/player.obj: player/player.c.obj
.PHONY : player/player.obj

# target to build an object file
player/player.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/player/player.c.obj
.PHONY : player/player.c.obj

player/player.i: player/player.c.i
.PHONY : player/player.i

# target to preprocess a source file
player/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/player/player.c.i
.PHONY : player/player.c.i

player/player.s: player/player.c.s
.PHONY : player/player.s

# target to generate assembly for a file
player/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/player/player.c.s
.PHONY : player/player.c.s

ui/ui.obj: ui/ui.c.obj
.PHONY : ui/ui.obj

# target to build an object file
ui/ui.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/ui/ui.c.obj
.PHONY : ui/ui.c.obj

ui/ui.i: ui/ui.c.i
.PHONY : ui/ui.i

# target to preprocess a source file
ui/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/ui/ui.c.i
.PHONY : ui/ui.c.i

ui/ui.s: ui/ui.c.s
.PHONY : ui/ui.s

# target to generate assembly for a file
ui/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/ui/ui.c.s
.PHONY : ui/ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... retro_game"
	@echo "... background/background.obj"
	@echo "... background/background.i"
	@echo "... background/background.s"
	@echo "... enemies/enemy.obj"
	@echo "... enemies/enemy.i"
	@echo "... enemies/enemy.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... player/player.obj"
	@echo "... player/player.i"
	@echo "... player/player.s"
	@echo "... ui/ui.obj"
	@echo "... ui/ui.i"
	@echo "... ui/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

