# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/longnguyen/Downloads/ppsspp/ppsspp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/longnguyen/Downloads/ppsspp/ppsspp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/longnguyen/Downloads/ppsspp/ppsspp/CMakeFiles /Users/longnguyen/Downloads/ppsspp/ppsspp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/longnguyen/Downloads/ppsspp/ppsspp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named retro_game

# Build rule for target.
retro_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 retro_game
.PHONY : retro_game

# fast build rule for target.
retro_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/build
.PHONY : retro_game/fast

background/background.obj: background/background.c.obj
.PHONY : background/background.obj

# target to build an object file
background/background.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/background/background.c.obj
.PHONY : background/background.c.obj

background/background.i: background/background.c.i
.PHONY : background/background.i

# target to preprocess a source file
background/background.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/background/background.c.i
.PHONY : background/background.c.i

background/background.s: background/background.c.s
.PHONY : background/background.s

# target to generate assembly for a file
background/background.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/background/background.c.s
.PHONY : background/background.c.s

bgm/bgmHandler.obj: bgm/bgmHandler.c.obj
.PHONY : bgm/bgmHandler.obj

# target to build an object file
bgm/bgmHandler.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/bgm/bgmHandler.c.obj
.PHONY : bgm/bgmHandler.c.obj

bgm/bgmHandler.i: bgm/bgmHandler.c.i
.PHONY : bgm/bgmHandler.i

# target to preprocess a source file
bgm/bgmHandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/bgm/bgmHandler.c.i
.PHONY : bgm/bgmHandler.c.i

bgm/bgmHandler.s: bgm/bgmHandler.c.s
.PHONY : bgm/bgmHandler.s

# target to generate assembly for a file
bgm/bgmHandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/bgm/bgmHandler.c.s
.PHONY : bgm/bgmHandler.c.s

enemies/enemy.obj: enemies/enemy.c.obj
.PHONY : enemies/enemy.obj

# target to build an object file
enemies/enemy.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/enemy.c.obj
.PHONY : enemies/enemy.c.obj

enemies/enemy.i: enemies/enemy.c.i
.PHONY : enemies/enemy.i

# target to preprocess a source file
enemies/enemy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/enemy.c.i
.PHONY : enemies/enemy.c.i

enemies/enemy.s: enemies/enemy.c.s
.PHONY : enemies/enemy.s

# target to generate assembly for a file
enemies/enemy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/enemy.c.s
.PHONY : enemies/enemy.c.s

enemies/mummy/mummy.obj: enemies/mummy/mummy.c.obj
.PHONY : enemies/mummy/mummy.obj

# target to build an object file
enemies/mummy/mummy.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/mummy/mummy.c.obj
.PHONY : enemies/mummy/mummy.c.obj

enemies/mummy/mummy.i: enemies/mummy/mummy.c.i
.PHONY : enemies/mummy/mummy.i

# target to preprocess a source file
enemies/mummy/mummy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/mummy/mummy.c.i
.PHONY : enemies/mummy/mummy.c.i

enemies/mummy/mummy.s: enemies/mummy/mummy.c.s
.PHONY : enemies/mummy/mummy.s

# target to generate assembly for a file
enemies/mummy/mummy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/mummy/mummy.c.s
.PHONY : enemies/mummy/mummy.c.s

enemies/slime/slime.obj: enemies/slime/slime.c.obj
.PHONY : enemies/slime/slime.obj

# target to build an object file
enemies/slime/slime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/slime/slime.c.obj
.PHONY : enemies/slime/slime.c.obj

enemies/slime/slime.i: enemies/slime/slime.c.i
.PHONY : enemies/slime/slime.i

# target to preprocess a source file
enemies/slime/slime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/slime/slime.c.i
.PHONY : enemies/slime/slime.c.i

enemies/slime/slime.s: enemies/slime/slime.c.s
.PHONY : enemies/slime/slime.s

# target to generate assembly for a file
enemies/slime/slime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/enemies/slime/slime.c.s
.PHONY : enemies/slime/slime.c.s

entity/entity.obj: entity/entity.c.obj
.PHONY : entity/entity.obj

# target to build an object file
entity/entity.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/entity/entity.c.obj
.PHONY : entity/entity.c.obj

entity/entity.i: entity/entity.c.i
.PHONY : entity/entity.i

# target to preprocess a source file
entity/entity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/entity/entity.c.i
.PHONY : entity/entity.c.i

entity/entity.s: entity/entity.c.s
.PHONY : entity/entity.s

# target to generate assembly for a file
entity/entity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/entity/entity.c.s
.PHONY : entity/entity.c.s

interactables/chest.obj: interactables/chest.c.obj
.PHONY : interactables/chest.obj

# target to build an object file
interactables/chest.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/interactables/chest.c.obj
.PHONY : interactables/chest.c.obj

interactables/chest.i: interactables/chest.c.i
.PHONY : interactables/chest.i

# target to preprocess a source file
interactables/chest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/interactables/chest.c.i
.PHONY : interactables/chest.c.i

interactables/chest.s: interactables/chest.c.s
.PHONY : interactables/chest.s

# target to generate assembly for a file
interactables/chest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/interactables/chest.c.s
.PHONY : interactables/chest.c.s

level/level.obj: level/level.c.obj
.PHONY : level/level.obj

# target to build an object file
level/level.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/level/level.c.obj
.PHONY : level/level.c.obj

level/level.i: level/level.c.i
.PHONY : level/level.i

# target to preprocess a source file
level/level.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/level/level.c.i
.PHONY : level/level.c.i

level/level.s: level/level.c.s
.PHONY : level/level.s

# target to generate assembly for a file
level/level.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/level/level.c.s
.PHONY : level/level.c.s

level/levelhandler.obj: level/levelhandler.c.obj
.PHONY : level/levelhandler.obj

# target to build an object file
level/levelhandler.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/level/levelhandler.c.obj
.PHONY : level/levelhandler.c.obj

level/levelhandler.i: level/levelhandler.c.i
.PHONY : level/levelhandler.i

# target to preprocess a source file
level/levelhandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/level/levelhandler.c.i
.PHONY : level/levelhandler.c.i

level/levelhandler.s: level/levelhandler.c.s
.PHONY : level/levelhandler.s

# target to generate assembly for a file
level/levelhandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/level/levelhandler.c.s
.PHONY : level/levelhandler.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/main.c.s
.PHONY : main.c.s

map/map.obj: map/map.c.obj
.PHONY : map/map.obj

# target to build an object file
map/map.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/map/map.c.obj
.PHONY : map/map.c.obj

map/map.i: map/map.c.i
.PHONY : map/map.i

# target to preprocess a source file
map/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/map/map.c.i
.PHONY : map/map.c.i

map/map.s: map/map.c.s
.PHONY : map/map.s

# target to generate assembly for a file
map/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/map/map.c.s
.PHONY : map/map.c.s

player/player.obj: player/player.c.obj
.PHONY : player/player.obj

# target to build an object file
player/player.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/player/player.c.obj
.PHONY : player/player.c.obj

player/player.i: player/player.c.i
.PHONY : player/player.i

# target to preprocess a source file
player/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/player/player.c.i
.PHONY : player/player.c.i

player/player.s: player/player.c.s
.PHONY : player/player.s

# target to generate assembly for a file
player/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/player/player.c.s
.PHONY : player/player.c.s

ui/ui.obj: ui/ui.c.obj
.PHONY : ui/ui.obj

# target to build an object file
ui/ui.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/ui/ui.c.obj
.PHONY : ui/ui.c.obj

ui/ui.i: ui/ui.c.i
.PHONY : ui/ui.i

# target to preprocess a source file
ui/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/ui/ui.c.i
.PHONY : ui/ui.c.i

ui/ui.s: ui/ui.c.s
.PHONY : ui/ui.s

# target to generate assembly for a file
ui/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/retro_game.dir/build.make CMakeFiles/retro_game.dir/ui/ui.c.s
.PHONY : ui/ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... retro_game"
	@echo "... background/background.obj"
	@echo "... background/background.i"
	@echo "... background/background.s"
	@echo "... bgm/bgmHandler.obj"
	@echo "... bgm/bgmHandler.i"
	@echo "... bgm/bgmHandler.s"
	@echo "... enemies/enemy.obj"
	@echo "... enemies/enemy.i"
	@echo "... enemies/enemy.s"
	@echo "... enemies/mummy/mummy.obj"
	@echo "... enemies/mummy/mummy.i"
	@echo "... enemies/mummy/mummy.s"
	@echo "... enemies/slime/slime.obj"
	@echo "... enemies/slime/slime.i"
	@echo "... enemies/slime/slime.s"
	@echo "... entity/entity.obj"
	@echo "... entity/entity.i"
	@echo "... entity/entity.s"
	@echo "... interactables/chest.obj"
	@echo "... interactables/chest.i"
	@echo "... interactables/chest.s"
	@echo "... level/level.obj"
	@echo "... level/level.i"
	@echo "... level/level.s"
	@echo "... level/levelhandler.obj"
	@echo "... level/levelhandler.i"
	@echo "... level/levelhandler.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map/map.obj"
	@echo "... map/map.i"
	@echo "... map/map.s"
	@echo "... player/player.obj"
	@echo "... player/player.i"
	@echo "... player/player.s"
	@echo "... ui/ui.obj"
	@echo "... ui/ui.i"
	@echo "... ui/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

